package com.myspace.app.ui.screen

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import com.myspace.app.ui.theme.DarkBackground
import com.myspace.app.ui.viewmodel.GeneratorViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun GeneratorScreen(onBack: () -> Unit, vm: GeneratorViewModel = hiltViewModel()) {
    var length by remember { mutableIntStateOf(20) }
    var upper by remember { mutableStateOf(true) }
    var lower by remember { mutableStateOf(true) }
    var digits by remember { mutableStateOf(true) }
    var symbols by remember { mutableStateOf(true) }
    var generated by remember { mutableStateOf("") }
    val ctx = LocalContext.current

    LaunchedEffect(Unit) { generated = vm.generate(length, upper, lower, digits, symbols) }

    Scaffold(
        containerColor = DarkBackground,
        topBar = {
            TopAppBar(
                title = { Text("Password Generator") },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = DarkBackground),
                navigationIcon = { IconButton(onClick = onBack) { Icon(Icons.AutoMirrored.Filled.ArrowBack, "Back") } }
            )
        }
    ) { padding ->
        Column(modifier = Modifier.padding(padding).padding(16.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
            // Generated password display
            ElevatedCard(modifier = Modifier.fillMaxWidth()) {
                Row(modifier = Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically) {
                    Text(
                        generated,
                        modifier = Modifier.weight(1f),
                        fontFamily = FontFamily.Monospace,
                        style = MaterialTheme.typography.bodyMedium
                    )
                    IconButton(onClick = { generated = vm.generate(length, upper, lower, digits, symbols) }) {
                        Icon(Icons.Default.Refresh, "Regenerate", tint = MaterialTheme.colorScheme.primary)
                    }
                    IconButton(onClick = {
                        val cm = ctx.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                        cm.setPrimaryClip(ClipData.newPlainText("password", generated))
                    }) {
                        Icon(Icons.Default.ContentCopy, "Copy")
                    }
                }
            }

            // Length slider
            Text("Length: $length", style = MaterialTheme.typography.labelMedium)
            Slider(value = length.toFloat(), onValueChange = { length = it.toInt() }, valueRange = 8f..64f, steps = 55)

            // Character set toggles
            @Composable fun Toggle(label: String, checked: Boolean, onToggle: (Boolean) -> Unit) {
                Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth()) {
                    Text(label, modifier = Modifier.weight(1f))
                    Switch(checked = checked, onCheckedChange = onToggle)
                }
            }
            Toggle("Uppercase (A-Z)", upper) { upper = it; generated = vm.generate(length, upper, lower, digits, symbols) }
            Toggle("Lowercase (a-z)", lower) { lower = it; generated = vm.generate(length, upper, lower, digits, symbols) }
            Toggle("Digits (0-9)", digits) { digits = it; generated = vm.generate(length, upper, lower, digits, symbols) }
            Toggle("Symbols (!@#…)", symbols) { symbols = it; generated = vm.generate(length, upper, lower, digits, symbols) }
        }
    }
}
